spring:
  datasource:
    url: jdbc:mysql://sfg-udemy.ccl7v4o6o9qe.eu-central-1.rds.amazonaws.com:3306/sfg_dev?useSSL=false
    username: sfg_dev_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true


